Models/DBClasses/Staff.cs
namespace BloodDonation.Models.DBClasses
{
    public class Staff
    {
        public int StaffID {  get; set; }
        public int UserID {  get; set; }
        public int YearsOfExperience {  get; set; }
        public string Role {  get; set; }

    }
}

Pages/Staff.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace BloodDonation.Pages
{
    public class StaffModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

Pages/Staff/Admin/Donors.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using BloodDonation.Models;
using BloodDonation.Models.DBClasses;
using System.Data;
using System.Data.SqlClient;
using System.Security.Cryptography.X509Certificates;
using System.ComponentModel.DataAnnotations;
namespace BloodDonation.Pages.Staff.Admin
{
    public class DonorsModel : PageModel
    {

        public DonorsModel(ILogger<DonorsModel> logger, DB dB)
        {

            _logger = logger;
            this.dB = dB;
        }


        [BindProperty]
        [Required]
        [StringLength(10, ErrorMessage = "The {0} must be at least {2} and at max {1} characters long.", MinimumLength = 10)]
        [DataType(DataType.PhoneNumber)]
        public string Phone { get; set; }

        [BindProperty]
        public string UserType { get; set; }

       

        [BindProperty]
        public string BloodType { get; set; }

        [BindProperty]
        public string Travel { get; set; }

        [BindProperty]
        public string MedicationHistory { get; set; }

        [BindProperty]
        [Required]
        [Range(1, 500, ErrorMessage = "Weight must be between 1 and 500.")]
        public string weight { get; set; }

        [BindProperty]
        public string Donation_interval_days { get; set; }

        [BindProperty]
        public string Donation_interval_months { get; set; }

        [BindProperty]
        public string Donation_interval_years { get; set; }


        public string donor { get; set; }
        public SqlConnection con { get; set; }
        private readonly ILogger<DonorsModel> _logger;
        private DB dB { get; set; }    
        public DataTable dt { get; set; }
        public Models.DBClasses.Donor d {  get; set; }

        public List<Models.DBClasses.Donor> Donor { get; set; } = new List<Models.DBClasses.Donor>();





        public void OnGet()
        {

            donor = "BloodType";

            dt = dB.ReadTable("Donor");

            for (int i = 0; i < dt.Rows.Count; i++)
            {

                d = new Models.DBClasses.Donor();

                d.DonorID = (int)dt.Rows[i]["DonorID"];
                d.BloodType = (string)dt.Rows[i]["BloodType"];
                d.Gender = (string)dt.Rows[i]["Gender"];
                d.Travel = (string)dt.Rows[i]["Travel"];
                d.MedicationHistory = (string)dt.Rows[i]["MedicationHistory"];
                d.Weight = (int)dt.Rows[i]["Weight"];
                d.IllnessHistory = (string)dt.Rows[i]["IllnessHistory"];
                d.DonationInterval = (string)dt.Rows[i]["DonationInterval"];
                d.EligibilityStatus = (string)dt.Rows[i]["EligibilityStatus"];
              

                Donor.Add(d);


            }
            Dictionary<String, String> keyValuePairs = new Dictionary<String, String>();
        }



        public IActionResult  OnPostDonors(string DonorID, string Name,
                                 string BirthdayDate,
                                 string Gender,
                                 string email,
                                 string Password,
                                 string Phone,
                                 string UserType,
                                 string BloodType,
                                 string Travel,
                                 string MedicationHistory,
                                 string  IllnessHistory,
                                 string Weight,
                                 string EligibilityStatus,
                                 string Donation_interval_days,
                                 string Donation_interval_months,
                                 string Donation_interval_years)
                                    
        {



            Dictionary<string, string> properties = new Dictionary<string, string>()
            {
                { "DonorID", DonorID },
                { "BloodType", BloodType },
                 { "Gender", Gender },
                 { "Travel", Travel },
                 { "MedicationHistory", MedicationHistory },
                  { "IllnessHistory", IllnessHistory },
                    { "DonationInterval", Donation_interval_days },
                { "Donation_interval_months", Donation_interval_months },
                { "Donation_interval_years", Donation_interval_years },
                { "Phone", Phone },
                {"EligabilityStatus",EligibilityStatus },
                {"Weight",Weight },
                {"TeamID",Weight },
                {"TeamLeaderID",Weight },
              


            };

            foreach (KeyValuePair<string, string> property in properties)
            {
                Console.WriteLine($"{property.Key}: {property.Value}");
            }
            (string, string) data = dB.AddDonor(properties);
            return RedirectToPage("/Staff/Admin/Donors");



            // public void Add(Dictionary<String, string> Dict)
            //    {

            //con.Open();
            //string Q = $"INSERT INTO [Donor] ([DonorID],BloodType,Gender,Travel,MedicationHistory,IllnessHistory,DonationInterval,EligabilityStatus,Weight,UserId,TeamId,TeamLeaderID) VALUES ('{Dict["DonorID"]}','{Dict["BloodType"]}','{Dict["Gender"]}','{Dict["Travel"]}','{Dict["MedicationHistory"]}','{Dict["IllnessHistory"]}','{Dict["DonationInterval"]}','{Dict["EligabilityStatus"]}','{Dict["Weight"]}','{Dict["UserId"]}','{Dict["TeamId"]}','{Dict["TeamLeaderID"]}');";

            //        SqlCommand cmd = new SqlCommand(Q, con);
            //        cmd = new SqlCommand(Q, con);



            //                cmd.ExecuteNonQuery();
            ////redirect to donor_main


            //con.Close();
            //        OnGet();





            //    }


        }
    }
}

Pages/Staff/Admin/Events.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using BloodDonation.Models;
using System.Data;
using System.ComponentModel.DataAnnotations;



namespace BloodDonation.Pages.Staff.Admin
{
    public class EventsModel : PageModel
    {

        private readonly ILogger<EventsModel> _logger;
        private DB dB { get; set; }
        public DataTable dt { get; set; }
        public Models.DBClasses.AnEvent e { get; set; }

        public List<Models.DBClasses.AnEvent> AnEvent { get; set; } = new List<Models.DBClasses.AnEvent>();



        public EventsModel(ILogger<EventsModel> logger, DB dB)
        {

            _logger = logger;
            this.dB = dB;
        }


        public string UserType { get; set; }

       
       

        public void OnPostEvents(
                                 string UserType
                                
                                )
        {
            Dictionary<string, string> properties = new Dictionary<string, string>()
            {
                { "UserType", UserType }
            };

            return;


        }


        public void OnGet()
        {



            dt = dB.ReadTable("AnEvent");

            for (int i = 0; i < dt.Rows.Count; i++)
            {

                e = new Models.DBClasses.AnEvent();

                e.EventID = (int)dt.Rows[i]["EventId"];
                e.EventDate = dt.Rows[i]["EventDate"].ToString();
                e.location = (string)dt.Rows[i]["location"];
                e.Description = (string)dt.Rows[i]["EventDescription"];
                e.Name = (string)dt.Rows[i]["Name"];
               

                AnEvent.Add(e);

            }



            Dictionary<String, String> keyValuePairs = new Dictionary<String, String>();



        }
    }

    
    
}

Pages/Staff/Admin/Staff.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using BloodDonation.Models;
using System.Data;
using System.ComponentModel.DataAnnotations;


namespace BloodDonation.Pages.Staff.Admin
{
    public class StaffModel : PageModel
    {
        private readonly ILogger<StaffModel> _logger;
        private DB dB { get; set; }
        public DataTable dt { get; set; }
        public Models.DBClasses.Staff s { get; set; }

        public List<Models.DBClasses.Staff> Staff { get; set; } = new List<Models.DBClasses.Staff>();



        public StaffModel(ILogger<StaffModel> logger, DB dB)
        {

            _logger = logger;
            this.dB = dB;
        }



        [BindProperty]
        [Required]
        public string Name { get; set; }

        [BindProperty]
        [Required]
        [DataType(DataType.Date)]
        public string BirthdayDate { get; set; }

        [BindProperty]
        [Required]
        public string Gender { get; set; }

        [BindProperty]
        [Required]
        [StringLength(100, ErrorMessage = "The {0} must be at least {2} and at max {1} characters long.", MinimumLength = 6)]
        [DataType(DataType.Password)]
        public string Password { get; set; }

        [BindProperty]
        [Required]
        [StringLength(10, ErrorMessage = "The {0} must be at least {2} and at max {1} characters long.", MinimumLength = 10)]
        [DataType(DataType.PhoneNumber)]
        public string Phone { get; set; }

        [BindProperty]
        public string UserType { get; set; }

        [BindProperty]
        public string Role { get; set; }

        [BindProperty]
        public string BloodType { get; set; }

        [BindProperty]
        public string Travel { get; set; }

        [BindProperty]
        public string MedicationHistory { get; set; }

        [BindProperty]
        [Required]
        [Range(1, 500, ErrorMessage = "Weight must be between 1 and 500.")]
        public string weight { get; set; }

        [BindProperty]
        public string Donation_interval_days { get; set; }

        [BindProperty]
        public string Donation_interval_months { get; set; }

        [BindProperty]
        public string Donation_interval_years { get; set; }

        public void OnGet()
        {



            dt = dB.ReadTable("Staff");

            for (int i = 0; i < dt.Rows.Count; i++)
            {

                s = new Models.DBClasses.Staff();

                s.StaffID = (int)dt.Rows[i]["StaffID"];
                s.YearsOfExperience = (int)dt.Rows[i]["YearsOfExperience"];
                s.Role = (string)dt.Rows[i]["Role"];


                Staff.Add(s);

            }





            Dictionary<String, String> keyValuePairs = new Dictionary<String, String>();

        }




        public IActionResult OnPostStaff(
                                    string Role,
                                 string UserType
                                )
        {
            Dictionary<string, string> properties = new Dictionary<string, string>()
            {
                
                { "UserType", UserType },
                 { "Role", Role }

            };

            foreach (KeyValuePair<string, string> property in properties)
            {
                Console.WriteLine($"{property.Key}: {property.Value}");
            }
            (string, string) data = dB.AddUserSignUp(properties);
            HttpContext.Session.SetString("UserID", data.Item2);
            Console.WriteLine(data);
            return RedirectToPage(data.Item1);


        }
    }
}

Pages/Staff/Admin/Steff.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace BloodDonation.Pages.Staff.Admin
{
    public class SteffModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

Pages/Staff/Admin/Teams.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using BloodDonation.Models;
using System.Data;


namespace BloodDonation.Pages.Staff.Admin
{
    public class TeamsModel : PageModel
    {

            private readonly ILogger<TeamsModel> _logger;
            private DB dB { get; set; }
            public DataTable dt { get; set; }
            public Models.DBClasses.Team t { get; set; }

            public List<Models.DBClasses.Team> Team { get; set; } = new List<Models.DBClasses.Team>();



            public TeamsModel(ILogger<TeamsModel> logger, DB dB)
            {

                _logger = logger;
                this.dB = dB;
            }


        public void OnGet()
        {



            dt = dB.ReadTable("Team");

            for (int i = 0; i < dt.Rows.Count; i++)
            {

                t = new Models.DBClasses.Team();

                t.TeamID = (int)dt.Rows[i]["TeamID"];
                t.Name = (string)dt.Rows[i]["Name"];


                Team.Add(t);

            }

        }
    }
}

Pages/Staff/Admin/admin.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using BloodDonation.Models;
using BloodDonation.Models.DBClasses;
using System.Data;
using System.Data.SqlClient;
using System.Security.Cryptography.X509Certificates;
using System.ComponentModel.DataAnnotations;




namespace BloodDonation.Pages.Staff.Admin


{
    public class adminModel : PageModel
    {
        private readonly ILogger<adminModel> _logger;
        private DB dB { get; set; }
        public DataTable dt { get; set; }
        public Models.DBClasses.Admin a { get; set; }

        public adminModel(ILogger<adminModel> logger, DB dB)
        {

            _logger = logger;
            this.dB = dB;
        }


       
        public void OnGet()
        {
        }
    }
}

Pages/Staff/Coordinator_main.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.Threading.Tasks;
using System.Data;

namespace BloodDonation.Pages.Staff
{
    public class Coordinator_mainModel : PageModel
    {
        public List<Event> Events { get; set; }

        public async Task<IActionResult> OnGetAsync()
        {
            await LoadEventsAsync();
            return Page();
        }

        public async Task<IActionResult> OnPostEditAsync(int id)
        {
            // Redirect to an edit page or handle edit logic here
            // Example: return RedirectToPage("/EditEvent", new { id });
            return Page();
        }

        public async Task<IActionResult> OnPostRemoveAsync(int id)
        {
            await RemoveEventAsync(id);
            await LoadEventsAsync(); // Reload events after removal
            return Page();
        }

        public async Task<IActionResult> OnPostAddAsync()
        {
            // Redirect to an add page or handle add logic here
            // Example: return RedirectToPage("/AddEvent");
            return Page();
        }

        private async Task LoadEventsAsync()
        {
            Events = new List<Event>();

            string connectionString = "Server=myServerAddress;Database=myDataBase;User Id=myUsername;Password=myPassword;"; // Replace with your actual connection string

            using (SqlConnection connection = new SqlConnection(connectionString))
            {
                await connection.OpenAsync();
                string query = "SELECT Id, Name, Date, Location, Description FROM Events";

                using (SqlCommand command = new SqlCommand(query, connection))
                {
                    using (SqlDataReader reader = await command.ExecuteReaderAsync())
                    {
                        while (await reader.ReadAsync())
                        {
                            Events.Add(new Event
                            {
                                Id = reader.GetInt32(0),
                                Name = reader.GetString(1),
                                Date = reader.GetDateTime(2),
                                Location = reader.GetString(3),
                                Description = reader.GetString(4)
                            });
                        }
                    }
                }
            }
        }

        private async Task RemoveEventAsync(int id)
        {
            string connectionString = "Server=myServerAddress;Database=myDataBase;User Id=myUsername;Password=myPassword;"; // Replace with your actual connection string

            using (SqlConnection connection = new SqlConnection(connectionString))
            {
                await connection.OpenAsync();
                string query = "DELETE FROM Events WHERE Id = @Id";

                using (SqlCommand command = new SqlCommand(query, connection))
                {
                    command.Parameters.AddWithValue("@Id", id);
                    await command.ExecuteNonQueryAsync();
                }
            }
        }

        public class Event
        {
            public int Id { get; set; }
            public string Name { get; set; }
            public DateTime Date { get; set; }
            public string Location { get; set; }
            public string Description { get; set; }
        }
    }
}

Pages/Staff/EditPage.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using BloodDonation.Models;


namespace BloodDonation.Pages.Staff
{
    public class EditPageModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

Pages/Staff/Coordinator_main.cshtml
@page
@model BloodDonation.Pages.Staff.Coordinator_mainModel
@{
    ViewData["Title"] = "Coordinator";
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
</head>
<body class="with-welcome-text">
    <div class="container-scroller d-flex flex-column">
        <nav class="navbar default-layout d-flex align-items-top flex-row">
            <div class="navbar-menu-wrapper d-flex align-items-top">
                <h1 class="welcome-text">Good Morning, <span class="text-black fw-bold">John Doe</span></h1>
            </div>
        </nav>
        <div class="container-fluid page-body-wrapper row col-lg-12">
            <div class="content-wrapper">
                <div class="row">
                    <div class="col-sm-12">
                        <div class="home-tab">
                            <div class="tab-content tab-content-basic">
                                <div class="tab-pane fade show active" id="overview" role="tabpanel" aria-labelledby="overview">
                                    <div class="row">
                                        <div class="col-lg-8 d-flex flex-column">
                                            <div class="row flex-grow">
                                                <div class="col-12 col-lg-4 col-lg-12 grid-margin stretch-card">
                                                    <div class="card card-rounded">
                                                        <div class="card-body">
                                                            <div class="d-sm-flex justify-content-between align-items-start">
                                                                <div>
                                                                    <h4 class="card-title card-title-dash">Events</h4>
                                                                </div>
                                                            </div>
                                                            <table class="table table-hover">
                                                                <thead>
                                                                    <tr>
                                                                        <th scope="col">#</th>
                                                                        <th scope="col">Name</th>
                                                                        <th scope="col">Date</th>
                                                                        <th scope="col">Location</th>
                                                                        <th scope="col">Description</th>
                                                                        <th scope="col"></th>
                                                                    </tr>
                                                                </thead>
                                                                <tbody>
                                                                    @foreach (var evt in Model.Events)
                                                                    {
                                                                        <tr>
                                                                            <th scope="row">@evt.Id</th>
                                                                            <td>@evt.Name</td>
                                                                            <td>@evt.Date.ToString("yyyy-MM-dd")</td>
                                                                            <td>@evt.Location</td>
                                                                            <td>@evt.Description</td>
                                                                            <td>
                                                                                <form method="post" asp-page-handler="Edit">
                                                                                    <input type="hidden" name="id" value="@evt.Id" />
                                                                                    <button type="submit" class="btn btn-primary">Edit</button>
                                                                                </form>
                                                                                <form method="post" asp-page-handler="Remove">
                                                                                    <input type="hidden" name="id" value="@evt.Id" />
                                                                                    <button type="submit" class="btn btn-primary">Remove</button>
                                                                                </form>
                                                                            </td>
                                                                        </tr>
                                                                    }
                                                                </tbody>
                                                            </table>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="col-lg-4 d-flex flex-column">
                                            <div class="row flex-grow">
                                                <div class="col-md-6 col-lg-12 grid-margin stretch-card">
                                                    <div class="card bg-primary card-rounded">
                                                        <div class="card-body pb-0">
                                                            <h4 class="card-title card-title-dash text-white mb-4">Events Summary</h4>
                                                            <div class="row">
                                                                <div class="col-sm-4">
                                                                    <p class="status-summary-ight-white text-white mb-1">Number of Events</p>
                                                                    <h2 class="text-info">357</h2>
                                                                </div>
                                                                <div class="col-sm-8">
                                                                    <div class="status-summary-chart-wrapper pb-4">
                                                                        <!--Add graph-->
                                                                    </div>
                                                                </div>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                                <div class="col-md-6 col-lg-12 grid-margin stretch-card">
                                                    <div class="card card-rounded">
                                                        <div class="card-body">
                                                            <div class="row">
                                                                <div class="col-lg-6">
                                                                    <div class="d-flex justify-content-between align-items-center mb-2 mb-sm-0">
                                                                        <div>
                                                                            <form method="post" asp-page-handler="Add">
                                                                                <button type="submit" class="btn btn-primary">Add an event</button>
                                                                            </form>
                                                                        </div>
                                                                    </div>
                                                                </div>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>
<script type="module" src="~/lib/chartjs/chart.umd.js"></script>
</html>

Pages/Staff/EditPage.cshtml
@page
@model BloodDonation.Pages.Staff.EditPageModel
@{
}