Models/DBClasses/Donor.cs
namespace BloodDonation.Models.DBClasses
{
    public class Donor
    {
        public int DonorID { get; set; }
        public string BloodType { get; set; }
        public string Gender { get; set; }
        public string Travel { get; set; }
        public string MedicationHistory { get; set; }
        public string IllnessHistory { get; set; }
        public string DonationInterval { get; set; }
        public string EligibilityStatus { get; set; }
        public int Weight { get; set; }
        public int UserID { get; set; }
        public int TeamID { get; set; }
        public int TeamLeaderID { get; set; }
    }
}

Pages/Admin.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace BloodDonation.Pages
{
    public class AdminModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

Pages/ChangePassword.cshtml.cs
using BloodDonation.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.ComponentModel.DataAnnotations;

namespace BloodDonation.Pages
{
    public class ChangePasswordModel : PageModel
    {
        private readonly ILogger<ChangePasswordModel> _logger;
        private DB dB { get; set; }
        public ChangePasswordModel(ILogger<ChangePasswordModel> logger, DB dB)
        {

            _logger = logger;
            this.dB = dB;
        }

        [BindProperty]
        [Required]
        [EmailAddress]
        public string email { get; set; }
        [BindProperty]
        [Required]
        public string newPassword { get; set; }
        [BindProperty]
        [Required]
        [Compare(nameof(newPassword), ErrorMessage = "The password and confirmation password do not match.")]
        public string confirmPassword { get; set; }
        public void OnGet()
        {
        }
        public IActionResult OnPostChangePassword()
        {
            if (ModelState.IsValid)
            {
            dB.changePassword(newPassword, email);
            return RedirectToPage("/Index");
            }
            else
            {
            return Page();

            }
        }
    }
}

Pages/Coordination.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace BloodDonation.Pages
{
    public class CoordinationModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

Pages/Donors.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace BloodDonation.Pages
{
    public class DonorsModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace BloodDonation.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }

}

Pages/Event.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace BloodDonation.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }

}

Pages/Index.cshtml.cs
using BloodDonation.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.ComponentModel.DataAnnotations;

namespace BloodDonation.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;
        private DB dB { get; set; }
        public IndexModel(ILogger<IndexModel> logger, DB dB) {

            _logger = logger;
            this.dB = dB;
        }
  
        [BindProperty]
        [Required]
        [EmailAddress]
        public string Email { get; set; }
        [BindProperty]
        [Required]
        [DataType(DataType.Password)]
        public string Password { get; set; }   

        public void OnGet()
        {
        }
        public IActionResult OnPostLogin(string email,string pass)
        {
            (string,string) data=dB.SignIn(email, pass);
            HttpContext.Session.Clear();
            HttpContext.Session.SetString("UserID",data.Item2);
            Console.WriteLine(data);
            return RedirectToPage(data.Item1);

        }
    }
}

Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace BloodDonation.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }

}

Pages/SignUp.cshtml.cs
using BloodDonation.Models;
using Microsoft.AspNetCore.Components;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.ComponentModel.DataAnnotations;

namespace BloodDonation.Pages
{
    public class SignUpModel : PageModel
    {
        private readonly ILogger<SignUpModel> _logger;
        private DB dB { get; set; }
        public SignUpModel(ILogger<SignUpModel> logger, DB dB)
        {

            _logger = logger;
            this.dB = dB;
        }


        [BindProperty]
        [Required]
        [EmailAddress]
        public string email { get; set; }

        [BindProperty]
        [Required]
        public string Name { get; set; }

        [BindProperty]
        [Required]
        [DataType(DataType.Date)]
        public string BirthdayDate { get; set; }

        [BindProperty]
        [Required]
        public string Gender { get; set; }

        [BindProperty]
        [Required]
        [StringLength(100, ErrorMessage = "The {0} must be at least {2} and at max {1} characters long.", MinimumLength = 6)]
        [DataType(DataType.Password)]
        public string Password { get; set; }

        [BindProperty]
        [Required]
        [StringLength(10, ErrorMessage = "The {0} must be at least {2} and at max {1} characters long.", MinimumLength = 10)]
        [DataType(DataType.PhoneNumber)]
        public string Phone { get; set; }

        [BindProperty]
        public string UserType { get; set; }

        [BindProperty]
        public string Role { get; set; }

        [BindProperty]
        public string BloodType { get; set; }

        [BindProperty]
        public string Travel { get; set; }

        [BindProperty]
        public string MedicationHistory { get; set; }

        [BindProperty]
        [Required]
        [Range(1, 500, ErrorMessage = "Weight must be between 1 and 500.")]
        public string weight { get; set; }

        [BindProperty]
        public string Donation_interval_days { get; set; }

        [BindProperty]
        public string Donation_interval_months { get; set; }

        [BindProperty]
        public string Donation_interval_years { get; set; }
        public void OnGet()
        {
            Dictionary<String, String> keyValuePairs = new Dictionary<String, String>();
        }

        public IActionResult OnPostSignUp(string Name,
                                 string BirthdayDate,
                                 string Gender,
                                 string email,
                                 string Password,
                                 string Phone,
                                 string UserType,
                                 string Role,
                                 string BloodType,
                                 string Travel,
                                 string MedicationHistory,
                                 string weight,
                                 string Donation_interval_days,
                                 string Donation_interval_months,
                                 string Donation_interval_years)
        {
            Dictionary<string, string> properties = new Dictionary<string, string>()
            {
                { "Name", Name },
                { "DateOfBirth", BirthdayDate },
                { "Gender", Gender },
                { "Email", email },
                { "Password", Password },
                { "Phone", Phone },
                { "UserType", UserType },
                { "Role", Role },
                { "BloodType", BloodType },
                { "Travel", Travel },
                { "MedicationHistory", MedicationHistory },
                { "Weight", weight },
                { "Donation_interval_days", Donation_interval_days },
                { "Donation_interval_months", Donation_interval_months },
                { "Donation_interval_years", Donation_interval_years }
            };

            foreach (KeyValuePair<string, string> property in properties)
            {
                Console.WriteLine($"{property.Key}: {property.Value}");
            }
            (string,string) data=dB.AddUserSignUp(properties);
            HttpContext.Session.SetString("UserID", data.Item2);
            Console.WriteLine(data);
            return RedirectToPage(data.Item1);


        }
    }
}

Pages/Staff.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace BloodDonation.Pages
{
    public class StaffModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

Pages/Staff/Admin/Donors.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using BloodDonation.Models;
using BloodDonation.Models.DBClasses;
using System.Data;
using System.Data.SqlClient;
using System.Security.Cryptography.X509Certificates;
using System.ComponentModel.DataAnnotations;
namespace BloodDonation.Pages.Staff.Admin
{
    public class DonorsModel : PageModel
    {

        public DonorsModel(ILogger<DonorsModel> logger, DB dB)
        {

            _logger = logger;
            this.dB = dB;
        }


        [BindProperty]
        [Required]
        [StringLength(10, ErrorMessage = "The {0} must be at least {2} and at max {1} characters long.", MinimumLength = 10)]
        [DataType(DataType.PhoneNumber)]
        public string Phone { get; set; }

        [BindProperty]
        public string UserType { get; set; }

       

        [BindProperty]
        public string BloodType { get; set; }

        [BindProperty]
        public string Travel { get; set; }

        [BindProperty]
        public string MedicationHistory { get; set; }

        [BindProperty]
        [Required]
        [Range(1, 500, ErrorMessage = "Weight must be between 1 and 500.")]
        public string weight { get; set; }

        [BindProperty]
        public string Donation_interval_days { get; set; }

        [BindProperty]
        public string Donation_interval_months { get; set; }

        [BindProperty]
        public string Donation_interval_years { get; set; }


        public string donor { get; set; }
        public SqlConnection con { get; set; }
        private readonly ILogger<DonorsModel> _logger;
        private DB dB { get; set; }    
        public DataTable dt { get; set; }
        public Models.DBClasses.Donor d {  get; set; }

        public List<Models.DBClasses.Donor> Donor { get; set; } = new List<Models.DBClasses.Donor>();





        public void OnGet()
        {

            donor = "BloodType";

            dt = dB.ReadTable("Donor");

            for (int i = 0; i < dt.Rows.Count; i++)
            {

                d = new Models.DBClasses.Donor();

                d.DonorID = (int)dt.Rows[i]["DonorID"];
                d.BloodType = (string)dt.Rows[i]["BloodType"];
                d.Gender = (string)dt.Rows[i]["Gender"];
                d.Travel = (string)dt.Rows[i]["Travel"];
                d.MedicationHistory = (string)dt.Rows[i]["MedicationHistory"];
                d.Weight = (int)dt.Rows[i]["Weight"];
                d.IllnessHistory = (string)dt.Rows[i]["IllnessHistory"];
                d.DonationInterval = (string)dt.Rows[i]["DonationInterval"];
                d.EligibilityStatus = (string)dt.Rows[i]["EligibilityStatus"];
              

                Donor.Add(d);


            }
            Dictionary<String, String> keyValuePairs = new Dictionary<String, String>();
        }



        public IActionResult  OnPostDonors(string DonorID, string Name,
                                 string BirthdayDate,
                                 string Gender,
                                 string email,
                                 string Password,
                                 string Phone,
                                 string UserType,
                                 string BloodType,
                                 string Travel,
                                 string MedicationHistory,
                                 string  IllnessHistory,
                                 string Weight,
                                 string EligibilityStatus,
                                 string Donation_interval_days,
                                 string Donation_interval_months,
                                 string Donation_interval_years)
                                    
        {



            Dictionary<string, string> properties = new Dictionary<string, string>()
            {
                { "DonorID", DonorID },
                { "BloodType", BloodType },
                 { "Gender", Gender },
                 { "Travel", Travel },
                 { "MedicationHistory", MedicationHistory },
                  { "IllnessHistory", IllnessHistory },
                    { "DonationInterval", Donation_interval_days },
                { "Donation_interval_months", Donation_interval_months },
                { "Donation_interval_years", Donation_interval_years },
                { "Phone", Phone },
                {"EligabilityStatus",EligibilityStatus },
                {"Weight",Weight },
                {"TeamID",Weight },
                {"TeamLeaderID",Weight },
              


            };

            foreach (KeyValuePair<string, string> property in properties)
            {
                Console.WriteLine($"{property.Key}: {property.Value}");
            }
            (string, string) data = dB.AddDonor(properties);
            return RedirectToPage("/Staff/Admin/Donors");



            // public void Add(Dictionary<String, string> Dict)
            //    {

            //con.Open();
            //string Q = $"INSERT INTO [Donor] ([DonorID],BloodType,Gender,Travel,MedicationHistory,IllnessHistory,DonationInterval,EligabilityStatus,Weight,UserId,TeamId,TeamLeaderID) VALUES ('{Dict["DonorID"]}','{Dict["BloodType"]}','{Dict["Gender"]}','{Dict["Travel"]}','{Dict["MedicationHistory"]}','{Dict["IllnessHistory"]}','{Dict["DonationInterval"]}','{Dict["EligabilityStatus"]}','{Dict["Weight"]}','{Dict["UserId"]}','{Dict["TeamId"]}','{Dict["TeamLeaderID"]}');";

            //        SqlCommand cmd = new SqlCommand(Q, con);
            //        cmd = new SqlCommand(Q, con);



            //                cmd.ExecuteNonQuery();
            ////redirect to donor_main


            //con.Close();
            //        OnGet();





            //    }


        }
    }
}

Pages/Staff/Admin/Events.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using BloodDonation.Models;
using System.Data;
using System.ComponentModel.DataAnnotations;



namespace BloodDonation.Pages.Staff.Admin
{
    public class EventsModel : PageModel
    {

        private readonly ILogger<EventsModel> _logger;
        private DB dB { get; set; }
        public DataTable dt { get; set; }
        public Models.DBClasses.AnEvent e { get; set; }

        public List<Models.DBClasses.AnEvent> AnEvent { get; set; } = new List<Models.DBClasses.AnEvent>();



        public EventsModel(ILogger<EventsModel> logger, DB dB)
        {

            _logger = logger;
            this.dB = dB;
        }


        public string UserType { get; set; }

       
       

        public void OnPostEvents(
                                 string UserType
                                
                                )
        {
            Dictionary<string, string> properties = new Dictionary<string, string>()
            {
                { "UserType", UserType }
            };

            return;


        }


        public void OnGet()
        {



            dt = dB.ReadTable("AnEvent");

            for (int i = 0; i < dt.Rows.Count; i++)
            {

                e = new Models.DBClasses.AnEvent();

                e.EventID = (int)dt.Rows[i]["EventId"];
                e.EventDate = dt.Rows[i]["EventDate"].ToString();
                e.location = (string)dt.Rows[i]["location"];
                e.Description = (string)dt.Rows[i]["EventDescription"];
                e.Name = (string)dt.Rows[i]["Name"];
               

                AnEvent.Add(e);

            }



            Dictionary<String, String> keyValuePairs = new Dictionary<String, String>();



        }
    }

    
    
}

Pages/Staff/Admin/Steff.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace BloodDonation.Pages.Staff.Admin
{
    public class SteffModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

Pages/ChangePassword.cshtml
@page
@model BloodDonation.Pages.ChangePasswordModel
@{
    ViewData["Title"] = "Change Password";
}
<style>
.gradient-custom-2 {
background: linear-gradient(to right, #ee7724, #d8363a, #dd3675, #b44593);
}

</style>

<section class="h-100 gradient-form" style="background-color: #eee;">
    <div class="container py-5 h-100">
        <div class="row d-flex justify-content-center align-items-center h-100">
            <div class="col-xl-10">
                <div class="card rounded-3 text-black">
                    <div class="row g-0">
                        <div class="col-lg-6">
                            <div class="card-body p-md-5 mx-md-4">

                                <div class="text-center">
                                    <img src="https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-login-form/lotus.webp"
                                         style="width: 185px;" alt="logo">
                                    <h4 class="mt-1 mb-5 pb-1">We are The Lotus Team</h4>
                                </div>

                                <form asp-page-handler="ChangePassword" method="post">
                                    <p>Forgot your account’s password? Enter your email address and the new Password </p>

                                    <div data-mdb-input-init class="form-outline mb-4">
                                        <label class="form-label" for="form2Example11">Email</label>
                                        <input type="email" asp-for="@Model.email" class="form-control"
                                               placeholder="Email address" />
                                        <span asp-validation-for="@Model.email" class="form-control"></span>
                                    </div>

                                    <div data-mdb-input-init class="form-outline mb-4">
                                        <label class="form-label" for="form2Example22">New Password</label>
                                        <input type="password" asp-for="@Model.newPassword" class="form-control" />
                                        <span asp-validation-for="@Model.newPassword" class="form-control"></span>
                                    </div>
                                    <div data-mdb-input-init class="form-outline mb-4">
                                        <label class="form-label" for="form2Example22">Duplicate Password</label>
                                        <input type="password" asp-for="@Model.confirmPassword" class="form-control" />
                                        <span asp-validation-for="@Model.confirmPassword" class="form-control"></span>
                                    </div>
                                    <div class="text-center pt-1 mb-5 pb-1">
                                        <input type="submit" value="Change" class="btn btn-primary btn-block fa-lg gradient-custom-2 mb-3" />
                                    </div>

                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

Pages/Event.cshtml
@page
@model PrivacyModel
@{
    
}
<h1>@ViewData["Title"]</h1>

<p>Thank you for your help!</p>

<div class="card-body">
    <div class="input-group mb-3">
        <input type="text" class="form-control" placeholder="Event Name" aria-label="Username" aria-describedby="basic-addon1">
    </div>
    <div class="input-group mb-3">
        <input type="text" class="form-control" placeholder="Location" aria-label="Username" aria-describedby="basic-addon1">
    </div>
    <div class="input-group mb-3">
        <span class="input-group-text" id="basic-addon1">Date</span>
        <input type="text" class="form-control" placeholder="Day" aria-label="Username" aria-describedby="basic-addon1">
        <input type="text" class="form-control" placeholder="Month" aria-label="Username" aria-describedby="basic-addon1">
        <input type="text" class="form-control" placeholder="Year" aria-label="Username" aria-describedby="basic-addon1">

    </div>
    <div class="input-group">
        <span class="input-group-text">Description</span>
        <textarea class="form-control" aria-label="With textarea"></textarea>
    </div>
</div>

Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}
<style>
.gradient-custom-2 {
background: linear-gradient(to right, #ee7724, #d8363a, #dd3675, #b44593);
}

</style>

<section class="h-100 gradient-form" style="background-color: #eee;">
    <div class="container py-5 h-100">
        <div class="row d-flex justify-content-center align-items-center h-100">
            <div class="col-xl-10">
                <div class="card rounded-3 text-black">
                    <div class="row g-0">
                        <div class="col-lg-6">
                            <div class="card-body p-md-5 mx-md-4">

                                <div class="text-center">
                                    <img src="https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-login-form/lotus.webp"
                                         style="width: 185px;" alt="logo">
                                    <h4 class="mt-1 mb-5 pb-1">We are The Lotus Team</h4>
                                </div>

                                <form asp-page-handler="Login" method="post">
                                    <p>Please login to your account</p>

                                    <div data-mdb-input-init class="form-outline mb-4">
                                        <label class="form-label" for="form2Example11">Username</label>
                                        <input type="email" name="email" class="form-control"
                                               placeholder="Phone number or email address" />
                                    </div>

                                    <div data-mdb-input-init class="form-outline mb-4">
                                        <label class="form-label" for="form2Example22">Password</label>
                                        <input type="password" name="pass" class="form-control" />
                                    </div>

                                    <div class="text-center pt-1 mb-5 pb-1">
                                        <input type="submit" value="Log in"  class="btn btn-primary btn-block fa-lg gradient-custom-2 mb-3" />
                                            
                                        <a class="text-muted" asp-page="ChangePassword">Forgot password?</a>
                                    </div>

                                </form>
                                <div class="d-flex align-items-center justify-content-center pb-4">
                                    <p class="mb-0 me-2">Don't have an account?</p>
                                    <a href="./SignUp" type="button" data-mdb-button-init data-mdb-ripple-init class="btn btn-outline-danger">Create new</a>
                                </div>

                            </div>
                        </div>
                        <div class="col-lg-6 d-flex align-items-center gradient-custom-2">
                            <div class="text-white px-3 py-4 p-md-5 mx-md-4">
                                <!-- EDIT THAT PART -->
                                <h4 class="mb-4">We are more than just a company</h4>
                                <p class="small mb-0">
                                    
                                    Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
                                    tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud
                                    exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
                                </p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

Pages/Staff.cshtml
@page
@model BloodDonation.Pages.StaffModel
@{
}

<div class="staff_id">
    <input type="text" class="form-control" placeholder="Your ID" aria-label="ID" aria-describedby="basic-addon1">
</div>
<br>
<div class="staff_name">
    <input type="text" class="form-control" placeholder="Name" aria-label="Username" aria-describedby="basic-addon1">
</div>
<br>
<div class="staff_age">
    <input type="number" class="form-control" placeholder="age" aria-label="age" aria-describedby="basic-addon1">
</div>
<br>
<div class="Experience_interval">

    <span class="input-group-text" id="basic-addon1">Experience interval</span>
    <input type="number" class="form-control" placeholder="Days" aria-label="Username" aria-describedby="basic-addon1">
    <input type="number" class="form-control" placeholder="Months" aria-label="Username" aria-describedby="basic-addon1">
    <input type="number" class="form-control" placeholder="Years" aria-label="Username" aria-describedby="basic-addon1">

</div>
<br>
<div class="staff_role">
    <input type="text" class="form-control" placeholder="Your role" aria-label="role" aria-describedby="basic-addon1">
</div>
<br>

Pages/Team.cshtml
@page
@model BloodDonation.Pages.TeamModel
@{
}
<div class="Team_id">
    <input type="text" class="form-control" placeholder="Your ID" aria-label="T_ID" aria-describedby="basic-addon1">
</div>
<br>
<div class="Team_name">
    <input type="text" class="form-control" placeholder="Name" aria-label="TeamName" aria-describedby="basic-addon1">
</div>
<br>
<div class="Leader_id">
    <input type="text" class="form-control" placeholder="Leader ID" aria-label="ID" aria-describedby="basic-addon1">
</div>
<br>